lines = [
    'import { useEffect, useState } from "react";',
    'import api from "../../api";',
    'import PageTransition from "../../components/PageTransition";',
    'import { toast } from "react-hot-toast";',
    'import { Plus, Trash2, Edit } from "lucide-react";',
    '',
    'export default function AdminProducts() {',
    '  const [products, setProducts] = useState([]);',
    '  const [loading, setLoading] = useState(true);',
    '',
    '  useEffect(() => {',
    '    fetchProducts();',
    '  }, []);',
    '',
    '  const fetchProducts = () => {',
    '    api.get("/products/")',
    '      .then((res) => setProducts(res.data.results || res.data))',
    '      .catch((err) => console.error(err))',
    '      .finally(() => setLoading(false));',
    '  };',
    '',
    '  const handleDelete = async (id) => {',
    '    if (!window.confirm("Are you sure you want to delete this product?")) return;',
    '    try {',
    '      await api.delete(/products//);',
    '      toast.success("Product deleted");',
    '      setProducts(products.filter(p => p.id !== id));',
    '    } catch (err) {',
    '      toast.error("Failed to delete product");',
    '      console.error(err);',
    '    }',
    '  };',
    '',
    '  if (loading) {',
    '    return (',
    '      <div className="space-y-4">',
    '        {[1, 2, 3].map((i) => (',
    '          <div key={i} className="h-24 animate-pulse rounded-2xl bg-slate-800/50" />',
    '        ))}',
    '      </div>',
    '    );',
    '  }',
    '',
    '  return (',
    '    <PageTransition>',
    '      <div className="space-y-6">',
    '        <div className="flex items-center justify-between">',
    '          <h1 className="text-2xl font-bold text-slate-100">Products Management</h1>',
    '          <button className="flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-indigo-600">',
    '            <Plus className="h-4 w-4" />',
    '            Add Product',
    '          </button>',
    '        </div>',
    '        ',
    '        <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/50">',
    '          <div className="overflow-x-auto">',
    '            <table className="w-full text-left text-sm text-slate-400">',
    '              <thead className="bg-slate-800/50 text-xs uppercase text-slate-300">',
    '                <tr>',
    '                  <th className="px-6 py-4 font-semibold">Image</th>',
    '                  <th className="px-6 py-4 font-semibold">Name</th>',
    '                  <th className="px-6 py-4 font-semibold">Category</th>',
    '                  <th className="px-6 py-4 font-semibold">Price</th>',
    '                  <th className="px-6 py-4 font-semibold">Stock</th>',
    '                  <th className="px-6 py-4 font-semibold text-right">Actions</th>',
    '                </tr>',
    '              </thead>',
    '              <tbody className="divide-y divide-slate-800">',
    '                {products.map((product) => (',
    '                  <tr key={product.id} className="hover:bg-slate-800/30">',
    '                    <td className="px-6 py-4">',
    '                      {product.image ? (',
    '                        <img src={product.image} alt={product.name} className="h-10 w-10 rounded-lg object-cover" />',
    '                      ) : (',
    '                        <div className="h-10 w-10 rounded-lg bg-slate-800" />',
    '                      )}',
    '                    </td>',
    '                    <td className="px-6 py-4 font-medium text-slate-200">',
    '                      {product.name}',
    '                    </td>',
    '                    <td className="px-6 py-4">',
    '                      <span className="rounded-full bg-slate-800 px-2 py-1 text-xs">{product.category}</span>',
    '                    </td>',
    '                    <td className="px-6 py-4">',
    '                      ',
    '                    </td>',
    '                    <td className="px-6 py-4">',
    '                      {product.stock > 0 ? (',
    '                        <span className="text-emerald-400">{product.stock} in stock</span>',
    '                      ) : (',
    '                        <span className="text-rose-400">Out of stock</span>',
    '                      )}',
    '                    </td>',
    '                    <td className="px-6 py-4 text-right">',
    '                      <div className="flex items-center justify-end gap-2">',
    '                        <button className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-800 hover:text-indigo-400">',
    '                          <Edit className="h-4 w-4" />',
    '                        </button>',
    '                        <button ',
    '                          onClick={() => handleDelete(product.id)}',
    '                          className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-800 hover:text-rose-400"',
    '                        >',
    '                          <Trash2 className="h-4 w-4" />',
    '                        </button>',
    '                      </div>',
    '                    </td>',
    '                  </tr>',
    '                ))}',
    '              </tbody>',
    '            </table>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </PageTransition>',
    '  );',
    '}'
]
with open('src/pages/admin/AdminProducts.jsx', 'w') as f:
    f.write('\\n'.join(lines))
