# Generated by Django 5.0.6 on 2026-08-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card (Stripe)'), ('upi_gpay', 'Google Pay (UPI)'), ('upi_paytm', 'Paytm (UPI)')], db_index=True, default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
