# Generated by Django 6.0.7 on 2026-08-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_order_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(db_index=True, default='USD', max_length=3),
        ),
    ]
