# Generated by Django 5.0.14 on 2026-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_promocode_first_order_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
