# Generated by Django 6.0.7 on 2026-08-26 06:00

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(db_index=True, default=apps.accounts.models.get_default_country, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(db_index=True, default=apps.accounts.models.get_default_currency, max_length=3),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country'], name='accounts_us_country_fe12a1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['currency'], name='accounts_us_currenc_f46ce6_idx'),
        ),
    ]
