# Generated by Django 5.0.14 on 2026-10-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('button_text', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='products.category')),
            ],
            options={
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
